Repository Skill-Forge-Project/skill_forge_frontend, pull requests merged in 2025-06, with the labels that each got.

#3 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/run-lint-check.yml
Labels: bug, enhancement

#2 ISSUE #308-2: Fix frontend registration form
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
Labels: bug

#4 ISSUE #8: Create New Quest - Form Enhancement
  src/components/Admin/AddQuest.jsx
Labels: enhancement

#6 ISSUE #5-2: Add refresh token functionality - Frontend Enhancement
  src/components/Admin/AddQuest.jsx
  src/components/Admin/EditQuestPage.jsx
  src/components/Admin/NewBoss.jsx
  src/components/Auth/LoginForm.jsx
  src/components/Layout/Navbar.jsx
  src/components/UserProfile/ProfileMain.jsx
  src/pages/ProfilePage.jsx
  src/pages/QuestPage.jsx
  src/services/authService.js
  src/services/questsServices.js
  src/services/underworldService.js
  src/services/useAvatarUrl.js
  src/services/usersService.js
Labels: enhancement
